package Picks;

sub get_picks
{
    # NOTE: the keys of this hash should be the entry name.  I have made them anonymous
    return {
        'CJ' => {
            paid => 1,
            champion => 'Netherlands',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Serbia', 'Germany' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'DN' => {
            paid => 1,
            champion => 'Brazil',
            group_picks => {
                A => [ 'Uruguay', 'France' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'Slovenia' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Paraguay', 'Italy' ],
                G => [ 'Brazil', 'Ivory Coast' ],
                H => [ 'Spain', 'Switzerland' ],
            },
        },
        'KCB' => {
            champion => 'Italy',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'Slovenia', 'England' ],
                D => [ 'Germany', 'Australia' ],
                E => [ 'Cameroon', 'Japan' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Ivory Coast', 'Portugal' ],
                H => [ 'Chile', 'Spain' ],
            },
        },
        'BW' => {
            paid => 1,
            champion => 'Spain',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Honduras' ],
            },
        },
        'TS' => {
            paid => 1,
            champion => 'Brazil',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'Algeria' ],
                D => [ 'Germany', 'Ghana' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Honduras' ],
            },
        },
        'CJ2' => {
            paid => 1,
            champion => 'Brazil',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'PW' => {
            paid => 1,
            champion => 'England',
            group_picks => {
                A => [ 'France', 'Uruguay' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Australia' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'TB' => {
            champion => 'Brazil',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'RA' => {
            paid => 1,
            champion => 'Spain',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'South Korea' ],
                C => [ 'Algeria', 'USA' ],
                D => [ 'Germany', 'Ghana' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Honduras' ],
            },
        },
        'LL' => {
            champion => 'England',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Cameroon', 'Netherlands' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Honduras' ],
            },
        },
        'BN' => {
            paid => 1,
            champion => 'Brazil',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Australia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Ivory Coast' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'JA' => {
            paid => 1,
            champion => 'Argentina',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'AA' => {
            champion => 'Spain',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'DN2' => {
            paid => 1,
            champion => 'Italy',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'South Korea' ],
                C => [ 'USA', 'England' ],
                D => [ 'Serbia', 'Germany' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Switzerland' ],
            },
        },
        'MN' => {
            champion => 'Argentina',
            group_picks => {
                A => [ 'France', 'South Africa' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Australia' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Switzerland' ],
            },
        },
        '(Fav)' => { # a hypothetical entry of all favorites
            champion => '',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
    };
}

1;
