package Picks;

sub get_picks
{
    # NOTE: the keys of this hash should be the entry name.  I have made them anonymous
    return {
        'A' => {
            paid => 1,
            champion => 'Netherlands',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Serbia', 'Germany' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'B' => {
            paid => 1,
            champion => 'Brazil',
            group_picks => {
                A => [ 'Uruguay', 'France' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'Slovenia' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Paraguay', 'Italy' ],
                G => [ 'Brazil', 'Ivory Coast' ],
                H => [ 'Spain', 'Switzerland' ],
            },
        },
        'C' => {
            champion => 'Italy',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'Slovenia', 'England' ],
                D => [ 'Germany', 'Australia' ],
                E => [ 'Cameroon', 'Japan' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Ivory Coast', 'Portugal' ],
                H => [ 'Chile', 'Spain' ],
            },
        },
        'D' => {
            paid => 1,
            champion => 'Spain',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Honduras' ],
            },
        },
        'E' => {
            paid => 1,
            champion => 'Brazil',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'Algeria' ],
                D => [ 'Germany', 'Ghana' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Honduras' ],
            },
        },
        'F' => {
            paid => 1,
            champion => 'Brazil',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'G' => {
            paid => 1,
            champion => 'England',
            group_picks => {
                A => [ 'France', 'Uruguay' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Australia' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'H' => {
            champion => 'Brazil',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'I' => {
            paid => 1,
            champion => 'Spain',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'South Korea' ],
                C => [ 'Algeria', 'USA' ],
                D => [ 'Germany', 'Ghana' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Honduras' ],
            },
        },
        'J' => {
            champion => 'England',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Cameroon', 'Netherlands' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Honduras' ],
            },
        },
        'K' => {
            paid => 1,
            champion => 'Brazil',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Australia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Ivory Coast' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'L' => {
            paid => 1,
            champion => 'Argentina',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'M' => {
            champion => 'Spain',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Slovakia' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
        'N' => {
            paid => 1,
            champion => 'Italy',
            group_picks => {
                A => [ 'Mexico', 'France' ],
                B => [ 'Argentina', 'South Korea' ],
                C => [ 'USA', 'England' ],
                D => [ 'Serbia', 'Germany' ],
                E => [ 'Netherlands', 'Cameroon' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Switzerland' ],
            },
        },
        'O' => {
            champion => 'Argentina',
            group_picks => {
                A => [ 'France', 'South Africa' ],
                B => [ 'Argentina', 'Greece' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Australia' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Switzerland' ],
            },
        },
        '(Favorites)' => { # a hypothetical entry of all favorites
            champion => '',
            group_picks => {
                A => [ 'France', 'Mexico' ],
                B => [ 'Argentina', 'Nigeria' ],
                C => [ 'England', 'USA' ],
                D => [ 'Germany', 'Serbia' ],
                E => [ 'Netherlands', 'Denmark' ],
                F => [ 'Italy', 'Paraguay' ],
                G => [ 'Brazil', 'Portugal' ],
                H => [ 'Spain', 'Chile' ],
            },
        },
    };
}

1;
